
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  internal_url: "http://192.168.1.129:8123"


command_line:
  - sensor:
      name: esb_usage_30min
      unique_id: esb_usage_30min
      command: "cat /config/www/esb_usage_30min.json"
      value_template: "{{ value_json.latest.value }}"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: measurement
      scan_interval: 900
      json_attributes:
        - source
        - granularity
        - unit
        - last_48h
  - sensor:
      name: esb_import_latest_kwh
      unique_id: esb_import_latest_kwh
      command: "cat /config/www/esb_usage_raw.json"
      value_template: >
        {% set rows = value_json if value_json is iterable else value_json.get('rows', []) %}
        {% set best = namespace(ts=0, v=none) %}
        {% for r in rows %}
          {% if r.get('Read Type','') | lower | contains('import') %}
            {% set t = strptime(r.get('Read Date and End Time',''), '%d-%m-%Y %H:%M') %}
            {% if t and as_timestamp(t) > best.ts %}
              {% set best.ts = as_timestamp(t) %}
              {% set kw = (r.get('Read Value') | string | replace(',', '.') | float) %}
              {% set best.v = kw * 0.5 %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {{ best.v | round(3) if best.v is not none else 'unknown' }}
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: measurement
      scan_interval: 900


