services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./media:/media
      - ./www:/config/www
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Dublin
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
