# This file defines sensors that poll data from external sources.
- platform: rest
  name: "ESB Usage 30min"
  unique_id: "esb_usage_30min_import"
  # --- ACTION REQUIRED ---
  # Replace the resource URL with the actual API endpoint for your smart meter data.
  resource: "https://api.esbnetworks.ie/v1/smart-meter-data"
  method: GET
  headers:
    # It's a best practice to store secrets like API keys outside your main configuration.
    Authorization: !secret esb_api_token
    Content-Type: "application/json"
  # Poll the API every 30 minutes (1800 seconds).
  scan_interval: 1800
  # --- ACTION REQUIRED ---
  # The template below assumes the API returns a JSON object with a "readings" array,
  # sorted from newest to oldest. You must adapt this to your API's response structure.
  # The 'state' of the sensor will be the most recent 30-minute usage value.
  value_template: >-
    {{ value_json.readings[0].value }}
  # The 'readings' attribute will store the full list of 30-minute values from the API,
  # fulfilling the requirement to have at least 48 hours of data available.
  json_attributes:
    - "readings"
  # These settings help Home Assistant understand and display the data correctly.
  unit_of_measurement: "kWh"
  device_class: "energy"
  state_class: "measurement"
